services:
  database:
    image: postgres:15
    ports:
      - "1934:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_DB: dev_db
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
